#pragma once

#define ONT_AMOUNT          "ONT Amount"
#define ONG_AMOUNT          "ONG Amount"
#define FROM                "From"
#define TO                  "To"
#define FEE_ONG             "Fee"
#define ONG_VIEW            " ONG"
#define ONT_VIEW            " ONT"
#define GAS_PRICE           "gasPrice"
#define GAS_LIMIT           "gasLimit"
#define SIGNER              "Signer"
#define SENDER              "sender"
#define DECIMALS            "Decimals"
#define DECIMALS_UNKNOWN    "Unknown"
#define AMOUNT              "Amount"
#define MSG                 "Message"
#define NBGL_MSG            "Message"
#define PEER_PUBKEY         "Public key"
#define NBGL_PEER_PUBKEY    "Operation wallet public key"
#define ACCOUNT             "Account"
#define INIT_POS            "init_pos"
#define ONT_ID              "ontId"
#define KEY_NO              "key_no"
#define TOTAL_WITHDRAW      "Total amount"
#define POS                 "Stake amount"
#define STAKE_FEE           "Starting fee"
#define STAKE_FEE_ONG       "500 ONG"
#define MAX_AUTHORIZE       "Allowed User Stake"
#define PEER_COST           "Fee Sharing Ratio (Node)"
#define STAKE_COST          "Fee Sharing Ratio (User)"
#define POS_LIST            "posList"
#define ADDRESS             "Address"
#define BLIND_SIGNING       "blind signing"
#define TOTAL_POS           "total pos"
#define NODE_AMOUNT         "Node amount"
#define ONE                 "1"
#define TWO                 "2"
#define THREE               "3"