#pragma once

#define ONT_AMOUNT          "ONT Amount"
#define ONG_AMOUNT          "ONG Amount"
#define FROM                "From"
#define TO                  "To"
#define FEE_ONG             "Fee"
#define GAS_FEE             "Gas fee"
#define PERCENTAGE          "%"
#define ONG_VIEW            " ONG"
#define ONT_VIEW            " ONT"
#define SIGNER              "Signer"
#define SENDER              "Sender"
#define DECIMALS            "Decimals"
#define DECIMALS_UNKNOWN    "Unknown"
#define AMOUNT              "Amount"
#define MSG                 "Message"
#define NBGL_MSG            "Message"
#define PEER_PUBKEY         "Public key"
#define NBGL_PEER_PUBKEY    "Operation wallet public key"
#define ACCOUNT             "Account"
#define INIT_POS            "init_pos"
#define ONT_ID              "ontId"
#define KEY_NO              "key_no"
#define TOTAL_WITHDRAW      "Total amount"
#define POS                 "Stake amount"
#define STAKE_FEE           "Starting fee"
#define STAKE_FEE_ONG       "500 ONG"
#define MAX_AUTHORIZE       "Allowed user stake"
#define PEER_COST           "Fee Sharing Ratio (Node)"
#define STAKE_COST          "Fee Sharing Ratio (User)"
#define POS_LIST            "posList"
#define ADDRESS             "Address"
#define BLIND_SIGNING       "Blind signing"
#define TOTAL_POS           "total pos"
#define NODE_AMOUNT         "Node amount"
#define ONE                 "1"
#define TWO                 "2"
#define THREE               "3"
#define BLIND_SIGN_TX       "Blind signing Transaction"
#define BLIND_SIGN_TX_MSG   "Accept risk and send"
#define VERIFY_ONT_ADDRESS      "Verify ONT address"

#define ADD_INIT_POS_TITLE                    "Review transaction to add initial stake"
#define ADD_INIT_POS_CONTENT                  "Sign transaction to add initial stake?"
#define SIGN_APPROVE_TX_TITLE                 "Review transaction to approve"
#define SIGN_APPROVE_TX_CONTENT               "Sign transaction to approve?"
#define AUTHORIZE_FOR_PEER_TITLE              "Review transaction to stake"
#define AUTHORIZE_FOR_PEER_CONTENT            "Sign transaction to stake?"
#define CHANGE_MAX_AUTHORIZATION_TITLE        "Review transaction to edit allowed user stake"
#define CHANGE_MAX_AUTHORIZATION_CONTENT      "Sign transaction to edit allowed user stake?"
#define OEP4_APPROVE_TITLE                    "Review transaction to approve"
#define OEP4_APPROVE_CONTENT                  "Sign transaction to approve?"
#define OEP4_TX_TITLE                         "Review transaction to send token"
#define OEP4_TX_CONTENT                       "Sign transaction to send token?"
#define PERSONAL_MSG_TITLE                    "Review message"
#define PERSONAL_MSG_CONTENT                  "Sign message?"
#define QUIT_NODE_TITLE                       "Review transaction to quit the node"
#define QUIT_NODE_CONTENT                     "Sign transaction to quit the node?"
#define REDUCE_INIT_POS_TITLE                 "Review transaction to reduce stake"
#define REDUCE_INIT_POS_CONTENT               "Sign transaction to reduce stake?"
#define REGISTER_CANDIDATE_TITLE              "Review transaction to register a node"
#define REGISTER_CANDIDATE_CONTENT            "Sign transaction to register a node?"
#define SET_FEE_PERCENTAGE_TITLE              "Review transaction to edit fee sharing ratio"
#define SET_FEE_PERCENTAGE_CONTENT            "Sign transaction to edit fee sharing ratio?"
#define NATIVE_ONG_OR_ONT_TRANSFER_TITLE      "Review transaction to send token"
#define NATIVE_ONG_OR_ONT_TRANSFER_CONTENT    "Sign transaction to send token?"
#define TRANSFER_FROM_TITLE                   "Review transaction"
#define TRANSFER_FROM_CONTENT                 "Sign transaction?"
#define UN_AUTHORIZE_FOR_PEER_TITLE           "Review transaction to unstake"
#define UN_AUTHORIZE_FOR_PEER_CONTENT         "Sign transaction to unstake?"
#define WITHDRAW_FEE_TITLE                    "Review transaction to claim ONG"
#define WITHDRAW_FEE_CONTENT                  "Sign transaction to claim ONG?"
#define WITHDRAW_TITLE                        "Review transaction to withdraw"
#define WITHDRAW_CONTENT                      "Sign transaction to withdraw?"
#define BLIND_SIGNING_TITLE                   "Review transaction"
#define BLIND_SIGNING_CONTENT                 "Accept risk and send transaction?"
