#pragma once

#define ONT_AMOUNT "ONT Amount"
#define ONG_AMOUNT "ONG Amount"
#define FROM   "from"
#define TO  "to"
#define FEE_ONG "Fee:ONG"
#define GAS_PRICE "gasPrice"
#define GAS_LIMIT "gasLimit"
#define SIGNER   "signer"
#define SENDER   "sender"
#define DECIMALS "decimals"
#define DECIMALS_UNKNOWN "decimals unknown"
#define AMOUNT "amount"
#define MSG "msg"
#define PEER_PUBKEY "peerPubkey"
#define ACCOUNT "account"
#define INIT_POS "init_pos"
#define ONT_ID "ontId"
#define KEY_NO "key_no"
#define TOTAL_WITHDRAW "total withdraw"
#define POS "pos"
#define MAX_AUTHORIZE "maxAuthorize"
#define PEER_COST "peerCost"
#define STAKE_COST "stakeCost"
#define POS_LIST "posList"
#define ADDRESS "Address"
#define BLIND_SIGNING "blind signing"